SOCIAL_AUTH_TWITTER_KEY = 'RmYhC39yrTsRahPrxpbTNIk9m'
SOCIAL_AUTH_TWITTER_SECRET = 'SEjo3pHKsuK6jnXuLoOfX7cZMbRMAzRlfiiRs4anWirhYbnGbU'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_URL = '/'
